### ISSUE TITLE
Vanilla Hopper won't pull an item from another hopper.

### ISSUE THREAD

**Issue by NTT1906** [ColinHDev/VanillaHopper#1]
Vanilla Hopper won't pull an item from another hopper. Otherwise, it will pull stuff out of its above hopper at twice as speed as normal making the hopper behave wrong.

P/s: Your is nice but I hate to say it but I didn't know there were so many hopper plugins, I already made two different hopper plugins bruh, just randomly scrolling poggit and found your.
So this is the feeling of wasting time ;-;

**Comment by NTT1906** [comment]
It would have a delay of 4 redstone ticks aka 8 game ticks or 0.4 seconds.

**Comment by ColinHDev** [comment]
> Vanilla Hopper won't pull an item from another hopper.
Actually, they do. This is called a "hopper pipe" and you can read about it in the wiki under https://minecraft.fandom.com/wiki/Hopper#Container_interactions.

But still, I tested it with the following contraption both in vanilla and on the server with the default settings.
![Screenshot (641)](https://user-images.githubusercontent.com/54852588/145410638-02b3da29-2871-4b6a-89cb-e8b01bb02bc3.png)
And both in vanilla and on the server, the hoppers took around 13s to move one stack of dirt from the upper to the lowest hopper.
64 items divided by 13 seconds equals exactly 4,9230769230769230769230769230769 or around 5 items per second, which is twice as fast as the normal amount of 2.5 items per second and as it is described in the wiki. (The inaccuracies are due to my measurement that is not 100% accurate to the decimal point.)
